---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - app/sa.yml # ServiceAccount for the application required for vault access
  # - app/config.yml  as these are not needed for vault setup and mangae through vault
  - app/dep.yml
  # - app/secret.yml  as these are not needed for vault setup and mangae through vault
  - app/svc.yml
  - app/hpa.yml
  - cron-job/cron-newsletter.yml
  - cron-job/cron-order.yml
  - database/database.yml
  - database/pv.yml
  - database/pvc.yml
  - database/secret.yml
  - database/svc.yml
