---
- name: Install kubectl
  hosts: master
  become: yes
  tasks:
    - name: Check if kubectl is already installed
      command: kubectl version --client
      register: kubectl_installed
      ignore_errors: yes

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
      when: kubectl_installed.rc != 0

    - name: Move kubectl to /usr/local/bin
      command: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
      when: kubectl_installed.rc != 0

    - name: Cleanup kubectl installer
      file:
        path: "/tmp/kubectl"
        state: absent
      when: kubectl_installed.rc != 0

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version
      when: kubectl_installed.rc != 0

    - debug:
        msg: "kubectl installed successfully: {{ kubectl_version.stdout }}"
      when: kubectl_installed.rc != 0
