---
- name: Install Trivy on Worker-CI
  hosts: worker_ci_group
  become: true  # Run as root
  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
        state: present

    - name: Add Trivy GPG Key
      shell: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      args:
        creates: /etc/apt/trivy-key-added

    - name: Add Trivy Repository
      shell: |
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
      args:
        creates: /etc/apt/sources.list.d/trivy.list

    - name: Update package list after adding Trivy repo
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present

    - name: Verify Trivy Installation
      command: trivy --version
      register: trivy_version
      changed_when: false

    - name: Display Trivy Version
      debug:
        msg: "Trivy Installed Version: {{ trivy_version.stdout }}"
