---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: marketverse
spec:
  template:
    spec:
      containers:
      - name: migration
        image: anonymous292009/migration:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://something:something@database-service.marketverse.svc.cluster.local:5432/database"
      restartPolicy: OnFailure
