---
# This file contains the Horizontal Pod Autoscaler (HPA) configuration for the Marketverse application.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: marketverse-hpa
  namespace: marketverse
  labels:
    app: marketverse
    chart: marketverse
    release: marketverse
    heritage: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marketverse-dep
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior: # don't that this does :)
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
