apiVersion: v1
kind: Secret
metadata:
  name: marketverse-secret
  namespace: marketverse
type: Opaque
data:
  CLERK_SECRET_KEY: your_clerk_secret_key
  CLOUDINARY_API_KEY: your_key
  CLOUDINARY_API_SECRET: your_secret
  SMTP_USER: your_user
  SMTP_PASSWORD: your_password
