apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: marketverse
spec:
  serviceName: 'database-service'
  replicas: 5
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: database-secret
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: database-storage
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
