apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: marketverse
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data/database'
