apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: marketverse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: database-pv
