apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: marketverse
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: database
  clusterIP: None # Headless service for StatefulSet
