apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-newsletter
  namespace: marketverse # Ensure it's in the same namespace as the service
spec:
  schedule: '0 10 * * 1' # At 10:00 AM, only on Monday
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-request
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - 'curl -X GET http://marketverse-svc:80/api/cron/newsletter'
          restartPolicy: OnFailure
